### ISSUE TITLE
Sometimes Getting exception when creating client object 

### ISSUE THREAD

**Issue by aadityapaliwal** [hashgraph/hedera-sdk-java#1606] opened 2023-09-13 17:53 UTC
### Description

We need to go live with our feature but on mainnet I am facing this issue when any of the request come from the dapp.  I am testing this in Realme XT API level 30 device. It seems to working fine in other Android device with API level 27. Use this demo project to repro - 

https://github.com/aadityapaliwal/WalletConnectDemo

### Steps to reproduce

- Use a Dapp.
- Pair with your wallet.
- From Dapp, use any transaction.
- On wallet we will get a request from dapp. To handle that, I am creating client object for query and signing .
- When below code runs, it throws an error on mainnet as well.

```
fun getClient() : Client {
        val client = Client.forName(networkName)
        client.setOperator(operatorAccountId(), operatorKey())
        return client
    }
```

### Additional context

Fatal Exception: java.lang.NoSuchMethodError: No static method delayedExecutor(JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/Executor;)Ljava/util/concurrent/Executor; in class Ljava/util/concurrent/CompletableFuture; or its super classes (declaration of 'java.util.concurrent.CompletableFuture' appears in /apex/com.android.art/javalib/core-oj.jar)
       at com.hedera.hashgraph.sdk.Delayer.delayFor(Delayer.java:70)
       at com.hedera.hashgraph.sdk.Client.scheduleNetworkUpdate(Client.java:350)
       at com.hedera.hashgraph.sdk.Client.<init>(Client.java:114)
       at com.hedera.hashgraph.sdk.Client.forMainnet(Client.java:181)
       at com.hedera.hashgraph.sdk.Client.forName(Client.java:163)
       at com.opencrowd.drop.common.HederaHashgraphManager.getClient(HederaHashgraphManager.kt:40)
       at com.opencrowd.drop.common.HederaHashgraphManager.getAccountBalance(HederaHashgraphManager.kt:46)
       at com.opencrowd.drop.ui.MainActivity.handleGetAccountBalanceRequest(MainActivity.kt:417)
       at com.opencrowd.drop.ui.MainActivity.access$handleGetAccountBalanceRequest(MainActivity.kt:59)
       at com.opencrowd.drop.ui.MainActivity$updateWalletConnectDelegates$walletDelegate$1.onSessionRequest(MainActivity.kt:285)
       at com.walletconnect.web3.wallet.client.Web3Wallet$setWalletDelegate$signWalletDelegate$1.onSessionRequest(Web3Wallet.kt:43)
       at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invokeSuspend(SignProtocol.kt:56)
       at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(:8)
       at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(:4)
       at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### Hedera network

mainnet

### Version

v2.27.0

### Operating system

macOS

**Comment by thenswan** [comment] 2023-09-18 13:34
Hey @aadityapaliwal, the fix for this issue is merged and will be available soon with the next release of the Java SDK 🙂

**Comment by aadityapaliwal** [comment] 2023-09-18 13:40
Thanks @thenswan

**Comment by aadityapaliwal** [comment] 2023-10-19 05:36
@thenswan I think it fix the above issue but still I am still facing the crash issue with the latest SDK version v2.29.0 and looks like the same no such method error but on a different place.

```
FATAL EXCEPTION: DefaultDispatcher-worker-6
                                                                                                    Process: cc.dropp.wallet, PID: 1771
                                                                                                    java.lang.NoSuchMethodError: No virtual method orTimeout(JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/CompletableFuture; in class Ljava/util/concurrent/CompletableFuture; or its super classes (declaration of 'java.util.concurrent.CompletableFuture' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:486)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.executeAsync(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:475)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.executeAsync(Query.java:51)
                                                                                                    	at com.opencrowd.drop.common.HederaHashgraphManager.getAccountBalance(HederaHashgraphManager.kt:56)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity.handleGetAccountBalanceRequest(MainActivity.kt:477)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity.access$handleGetAccountBalanceRequest(MainActivity.kt:56)
                                                                                                    	at com.opencrowd.drop.ui.MainActivity$updateWalletConnectDelegates$walletDelegate$1.onSessionRequest(MainActivity.kt:345)
                                                                                                    	at com.walletconnect.web3.wallet.client.Web3Wallet$setWalletDelegate$signWalletDelegate$1.onSessionRequest(Web3Wallet.kt:43)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invokeSuspend(SignProtocol.kt:56)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:8)
                                                                                                    	at com.walletconnect.sign.client.SignProtocol$setWalletDelegate$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@59598df, Dispatchers.IO]
```

Check the screenshot of the crashlytics as well
<img width="1241" alt="Screenshot 2023-10-19 at 11 03 38 AM" src="https://github.com/hashgraph/hedera-sdk-java/assets/92382212/bd5c44c7-606b-4902-a1d8-7e1a6db64965">

**Comment by aadityapaliwal** [comment] 2023-10-19 05:38
@thenswan Can we reopen it?

**Comment by thenswan** [comment] 2023-10-19 08:04
Hey @aadityapaliwal, will check it

**Comment by thenswan** [comment] 2023-10-19 08:39
@aadityapaliwal, can you please try the following steps and let me know if it will solve your issue:
1. Run gradle `clean`
2. Run gradle `build --refresh-dependencies`

If this will not solve your issue:
1. If there are some new updates for [your repo](https://github.com/aadityapaliwal/WalletConnectDemo) - please update it, so I can reproduce the issue.
2. [This link](https://dropp-walletconnect-testbed.s3.amazonaws.com/index.html) is not accessible to me anymore, so I can't go through the steps to reproduce the issue.

**Comment by aadityapaliwal** [comment] 2023-10-19 10:50
@thenswan I tried the same you mentioned but it's still crashing. Let me the update the changes in my repo.

Please use this website https://dropp-walletconnect-testbed.dropp.cc/ to connect.

**Comment by thenswan** [comment] 2023-10-19 11:15
@aadityapaliwal understood. Please ping me when you will update the repo.

**Comment by aadityapaliwal** [comment] 2023-10-19 11:44
@thenswan I have updated the repo with new changes. I am getting same issue there as well. Please check.

```
java.lang.NoSuchMethodError: No virtual method orTimeout(JLjava/util/concurrent/TimeUnit;)Ljava/util/concurrent/CompletableFuture; in class Ljava/util/concurrent/CompletableFuture; or its super classes (declaration of 'java.util.concurrent.CompletableFuture' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:486)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.executeAsync(Query.java:51)
                                                                                                    	at com.hedera.hashgraph.sdk.Executable.executeAsync(Executable.java:475)
                                                                                                    	at com.hedera.hashgraph.sdk.Query.executeAsync(Query.java:51)
```

Don't forget to the update the operator_acc_id, pvt_key, and public key in the strings.xml file

**Comment by thenswan** [comment] 2023-10-19 12:23
@aadityapaliwal can you please clarify at which step of the flow you have an error that you mentioned?
Also, for me now it looks like nothing is changing in the web app when I approve the session (before it did).

**Comment by thenswan** [comment] 2023-10-19 13:44
Thanks, @aadityapaliwal, I would like to add to my reply above that the app is not crashing for me. Also, please let me know the Android API levels on devices that you are testing with.

**Comment by aadityapaliwal** [comment] 2023-10-20 04:20
Hi @thenswan 

Can you please check the Dapp? It should connect now and show you the options to request. If it doesn't work in normal browser, please give it a try on incognito mode.

I am using Android 11 (API level 30).

**Comment by thenswan** [comment] 2023-10-20 06:50
Thanks @aadityapaliwal, will check

**Comment by thenswan** [comment] 2023-10-23 07:08
Hey @aadityapaliwal,

Information below might unblock you, while you are waiting for a new Hedera Java SDK version to be released. 

- Working on SDK levels 26, 27, 31, 32, and 33:
    
    ```
    AccountInfoQuery().setAccountId(operatorId).execute(client)
    
    ```
    
- Not working on SDK levels 28, 29, and 30:
    
    ```
    AccountBalanceQuery().setAccountId(operatorId).executeAsync(client)
    
    ```

**Closed** 2023-10-24 06:50 UTC
Labels: bug
