### ISSUE TITLE
All log flood with 503 Service Unavailable, topic message submit does not work on mainnet

### ISSUE THREAD

**Issue by astudnev** [hashgraph/hedera-sdk-java#441] opened 2020-12-17 08:25 UTC
I use SDK v 2.0.2 ( and previously used 1.0.3

Got the same issue - the code that works on testnet, does not work on mainnet.

On submit message it generates a lot of errors. 

My code is:

```
this.client = (NETWORK.equals("testnet") ? Client.forTestnet() : Client.forMainnet());
        client.setOperator(OPERATOR_ID, OPERATOR_KEY);
        if(topic==null){
            topic = createTopic();
        }
        this.topicId = TopicId.fromString(topic);

new TopicMessageSubmitTransaction()
                    .setTopicId(topicId)
                    .setMessage(mapper.writeValueAsString( message ))
                    .execute(client);


```

I do not configure any node list 

```
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.lang.Thread.run(Thread.java:834)
Dec 17 08:18:18 node1-3 java[4132]: [hedera-sdk-11] ERROR com.hedera.hashgraph.sdk.Executable - caught error, retrying
Dec 17 08:18:18 node1-3 java[4132]: node=0.0.9
Dec 17 08:18:18 node1-3 java[4132]: attempt=1
Dec 17 08:18:18 node1-3 java[4132]: delay=250
Dec 17 08:18:18 node1-3 java[4132]: {}
Dec 17 08:18:18 node1-3 java[4132]: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503
Dec 17 08:18:18 node1-3 java[4132]: invalid content-type: text/html
Dec 17 08:18:18 node1-3 java[4132]: headers: Metadata(:status=503,content-length=107,cache-control=no-cache,content-type=text/html)
Dec 17 08:18:18 node1-3 java[4132]: DATA-----------------------------
Dec 17 08:18:18 node1-3 java[4132]: <html><body><h1>503 Service Unavailable</h1>
Dec 17 08:18:18 node1-3 java[4132]: No server is available to handle this request.
Dec 17 08:18:18 node1-3 java[4132]: </body></html>
Dec 17 08:18:18 node1-3 java[4132]: DATA-----------------------------
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.Status.asRuntimeException(Status.java:533)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.lang.Thread.run(Thread.java:834)
Dec 17 08:18:18 node1-3 java[4132]: [hedera-sdk-8] ERROR com.hedera.hashgraph.sdk.Executable - caught error, retrying
Dec 17 08:18:18 node1-3 java[4132]: node=0.0.9
Dec 17 08:18:18 node1-3 java[4132]: attempt=1
Dec 17 08:18:18 node1-3 java[4132]: delay=250
Dec 17 08:18:18 node1-3 java[4132]: {}
Dec 17 08:18:18 node1-3 java[4132]: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP status code 503
Dec 17 08:18:18 node1-3 java[4132]: invalid content-type: text/html
Dec 17 08:18:18 node1-3 java[4132]: headers: Metadata(:status=503,content-length=107,cache-control=no-cache,content-type=text/html)
Dec 17 08:18:18 node1-3 java[4132]: DATA-----------------------------
Dec 17 08:18:18 node1-3 java[4132]: <html><body><h1>503 Service Unavailable</h1>
Dec 17 08:18:18 node1-3 java[4132]: No server is available to handle this request.
Dec 17 08:18:18 node1-3 java[4132]: </body></html>
Dec 17 08:18:18 node1-3 java[4132]: DATA-----------------------------
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.Status.asRuntimeException(Status.java:533)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
Dec 17 08:18:18 node1-3 java[4132]:         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Dec 17 08:18:18 node1-3 java[4132]:         at java.base/java.lang.Thread.run(Thread.java:834)
Dec 17 08:18:18 node1-3 java[4132]: [hedera-sdk-0] ERROR com.hedera.hashgraph.sdk.Executable - caught error, retrying
Dec 17 08:18:18 node1-3 java[4132]: node=0.0.9

```

**Comment by astudnev** [comment] 2020-12-17 13:29
It resolved when i provided list of the first 4 accounts, but the default configuration must be more fault tolerant. Now it even hangs up on querying receipt

**Comment by danielakhterov** [comment] 2020-12-29 06:43
I believe this was caused by node prioritization being incorrectly implemented. I believe this should now be fixed on master since using `Client.forMainnet()` no longer seems throw an error on executing the first transaction.
@astudnev can you try to reproduce this issue using the latest master branch.

**Comment by danielakhterov** [comment] 2021-03-26 23:02
Stale issue; closing.

**Closed by danielakhterov** 2021-03-26 23:02 UTC
